# Generated by Django 5.0.6 on 2024-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=34)),
                ('gender', models.CharField(max_length=23)),
                ('marks', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
